Vagrant.configure("2") do |config|

   config.vm.define "tutorial" do |t|
     t.vm.box = "centos/7"
     t.vm.network "private_network", ip: "10.1.1.31"
     t.vm.provider "virtualbox" do |v|
       v.memory = 2024
     end

   end

end
